routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', 'LoginController@logout')->name('logout');
Route::get('/register', 'RegisterController@index')->name('register');
Route::post('/register', 'RegisterController@store')->name('register.execute');

Route::group(['middleware' => 'access.guest'], function(){
  Route::get('/login', 'LoginController@index')->name('login');
  Route::post('/login', 'LoginController@verify')->name('login.verify');
});

Route::group(['middleware' => 'access.auth'], function(){
  Route::get('teams/details/{id}', 'User\TeamController@details')->name('team.details.company');
  Route::get('profileOf/{id}', 'UserController@profile')->name('profileof.view');
  Route::get('contest/{id}', 'Company\ContestController@show_public')->name('contest.public.details');
  Route::get('message/{id}', 'UserController@getMessage')->name('messageOf');
  Route::post('message/{id}', 'UserController@sendMessage')->name('messageOf');

  Route::get('messages', 'UserController@messages')->name('message');

  Route::get('browse/users', 'CommonController@browse_users')->name('browse.users');
  Route::post('browse/users', 'CommonController@search_users')->name('browse.users.search');
  Route::get('browse/teams', 'CommonController@browse_teams')->name('browse.teams');
  Route::post('browse/teams', 'CommonController@search_teams')->name('browse.teams.search');
  Route::get('browse/contests', 'CommonController@browse_contests')->name('browse.contests');
  Route::post('browse/contests', 'CommonController@search_contests')->name('browse.contests.search');


  Route::group(['prefix' => 'user', 'middleware' => 'access.user'], function(){
    Route::get('/', 'User\HomeController@index')->name('user.home');

    Route::resource('profile', 'User\ProfileController', ['except' => 'show']);
    Route::get('profile/change/password', 'User\ProfileController@showchangepass')->name('user.pass.change');
    Route::post('profile/change/password', 'User\ProfileController@changepass')->name('user.pass.changing');
    Route::resource('projects', 'User\ProjectController');

    Route::get('contests', 'User\ContestController@index')->name('user.contests.index');
    Route::post('contests/join', 'User\ContestController@join')->name('user.contests.join');
    Route::post('contests', 'User\ContestController@participate')->name('user.contests.participate');
    Route::delete('contests/cancel', 'User\ContestController@cancel')->name('user.contests.cancel');

    Route::get('teams', 'User\TeamController@index')->name('team');

    Route::get('teams/create', 'User\TeamController@create')->name('team.create');
    Route::post('teams/create', 'User\TeamController@store')->name('team.store');

    Route::get('teams/edit/{id}', 'User\TeamController@edit')->name('team.edit');
    Route::post('teams/edit/{id}', 'User\TeamController@update')->name('team.update');

    Route::get('teams/details/{id}', 'User\TeamController@details')->name('team.details');

    Route::get('teams/searchuser/{id}', 'User\TeamController@searchuser')->name('team.searchuser');
    Route::post('teams/searchuser/{id}', 'User\TeamController@searchresult')->name('team.searchresult');

    Route::get('projects/searchteam/{id}', 'User\ProjectController@searchteam')->name('project.searchteam');
    Route::post('projects/searchteam/{id}', 'User\ProjectController@searchresult')->name('project.searchteam');
    Route::get('projects/leave/{id}/{lid}','User\ProjectController@pro_leave')->name('project.leave');

    Route::get('teams/invite/{teamid}/{userid}', 'User\TeamController@invite')->name('team.invite');
    Route::get('project/invite/{projectid}/{teamid}', 'User\ProjectController@invite')->name('project.invite');

    Route::get('teams/requests', 'User\TeamController@requests')->name('team.requests');
    Route::get('project/requests', 'User\ProjectController@requests')->name('project.requests');

    Route::get('project/decline/{id}', 'User\ProjectController@reqdecline')->name('project.decline');
    Route::get('project/accept/{id}', 'User\ProjectController@reqaccept')->name('project.accept');


    Route::get('teams/accept/{id}', 'User\TeamController@reqaccept')->name('team.accept');
    Route::get('teams/decline/{id}', 'User\TeamController@reqdecline')->name('team.decline');

    Route::get('teams/reqcancel/{teamid}/{userid}', 'User\TeamController@cancel')->name('team.reqcancel');
    Route::get('teams/memremove/{teamid}/{userid}', 'User\TeamController@memremove')->name('team.memremove');

    Route::get('project/requests/details/{projectid}/{teamid}/{userid}', 'User\ProjectController@reqdetails')->name('project.reqdetails');


    Route::get('offers', 'User\OfferController@index')->name('offers');
    Route::get('offers/accept/{id}', 'User\OfferController@accept')->name('offers.accept');
    Route::get('offers/decline/{id}', 'User\OfferController@decline')->name('offers.decline');
    Route::get('offers/details/{id}', 'User\OfferController@companydetails')->name('offers.companydetails');
  });

  Route::group(['prefix' => 'company', 'middleware' => 'access.company'], function(){
    Route::get('/', 'Company\HomeController@index')->name('company.home');

    Route::resource('companyprofile', 'Company\ProfileController', ['except' => 'show']);

    Route::resource('contests', 'Company\ContestController');
    Route::post('contests/request', 'Company\ContestController@request')->name('contests.request');

    Route::get('contests/invitations/list', 'Company\ContestController@show_invitation_list')->name('company.invitations.list');

    Route::post('contests/invitations/accept', 'Company\ContestController@invitation_accept')->name('company.invitations.accept');
    Route::post('contests/invitations/reject', 'Company\ContestController@invitation_reject')->name('company.invitations.reject');

    Route::post('contests/find/company', 'UserController@search_companies_by_name')->name('companies.find.by.name');

    Route::get('contests/{contest_id}/companies/invite', 'Company\ContestController@new_invite')->name('company.new.invite');
    Route::post('contests/companies/invite', 'Company\ContestController@request_invite')->name('company.request.invite');




    Route::get('review/{participant_id}/project/{project_id}/', 'Company\ReviewController@show')->name('company.review.show');
    Route::post('review/declare', 'Company\ReviewController@declare')->name('company.review.declare');
    Route::post('review/reject', 'Company\ReviewController@reject')->name('company.review.reject');

    Route::get('hires', 'Company\HireController@index')->name('hire.index');
    Route::post('hires', 'Company\HireController@searchresult')->name('hire.searchresult');
    Route::get('hires/userdetails/{id}', 'Company\HireController@userdetails')->name('userdetails');
    Route::post('hires/invite/', 'Company\HireController@hire')->name('hire.invite');
    Route::get('hires/invitations', 'Company\HireController@invitelist')->name('invitations');

  });

});

resources/views/alerts.blade.php
@if (Session::has('success'))
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success !</strong> {{ Session::get('success') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
@endif

@if (Session::has('fail'))
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Failed !</strong> {{ Session::get('fail') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
@endif

@if (Session::has('info'))
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <strong>Note !</strong> {{ Session::get('info') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
@endif

@if (count($errors) > 0)
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Failed !</strong> For the following reasons -
    <ul>
      @foreach ($errors->all() as $error)
        <li>
          {{ $error }}
        </li>
      @endforeach
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
@endif

resources/views/login.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
</head>
<body>
	<table border="0" width="100%">
		<tr>
			<td width="100"></td>
			<td align="center">
				<h1>Login</h1>
			</td>
			<td width="100"></td>
		</tr>
		<tr>
			<td width="100"></td>
			<td align="center">
				<hr/>
			</td>
			<td width="100"></td>
		</tr>
		<tr>
			<td width="100"></td>
			<td>
				<br/>
				<br>
				<center>
					<div class="panel panel-default" style="background-color:#343A40;"><br><br>
	  <div class="panel-body">
					<form method="post" action="{{route('login.verify')}}">
						{{ csrf_field() }}
						<table>
							<tr>
								<td></td>
								<td>
									<div class="input-group">
								    <span class="input-group-addon"><label style="margin-right:29px">Email:</label></span>
								    <input type="text" class="form-control" name="Email" placeholder="Email">
								  </div>
							</tr>
							<tr>
								<td></td>
								<td>
									<div class="input-group">
									<span class="input-group-addon"><label>Password:</label></span>
									<input type="password" class="form-control" name="Pass" placeholder="Password">
								</div>
							</tr>
							<tr>
								<td></td>
								<td><br><center><input type="submit" class="btn btn-success" value="Login"></center></td>
							</tr>
							<tr>
								<td></td>
								<td>
									<br><label style="margin-left:10px">Not A Member? Click <a href="{{route('register')}}">here</a> to register</label>
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
					<br/>
					<br/>
					<div>
						@if(Session::has('success'))
							<p style="color: green;">{{ Session::get('success') }}</p>
						@endif
						@if(Session::has('fail'))
							<p style="color: red;">{{ Session::get('fail') }}</p>
						@endif
					</div>
					<div>
						@if($errors->any())
						@foreach($errors->all() as $err)
						<p>Error: {{$err}}</p>
						@endforeach
						@endif
					</div>
				</center>
			</td>
			<td width="100"></td>
		</tr>
	</table>
</body>
</html>
<style>
body{
	background-color:#343A40;
	color:white;
}
</style>

resources/views/menu.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Main Font -->
	<script src="{{ asset('default/js/webfontloader.min.js') }}"></script>
	<script>
		WebFont.load({
			google: {
				families: ['Roboto:300,400,500,700:latin']
			}
		});
	</script>

  <title>Collabs @yield('title')</title>

  <!-- Bootstrap core CSS-->
  <link rel="stylesheet" type="text/css" href="{{ asset('default/Bootstrap/dist/css/bootstrap-reboot.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('default/Bootstrap/dist/css/bootstrap.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('default/Bootstrap/dist/css/bootstrap-grid.css') }}">




<!-- Theme Styles CSS -->
<link rel="stylesheet" type="text/css" href="{{ asset('default/css/theme-styles.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('default/css/blocks.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('default/css/fonts.css') }}">

<!-- Styles for plugins -->
<link rel="stylesheet" type="text/css" href="{{ asset('default/css/jquery.mCustomScrollbar.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('default/css/daterangepicker.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('default/css/bootstrap-select.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('default/css/swiper.min.css') }}">

<!-- Lightbox popup script-->
<link rel="stylesheet" type="text/css" href="{{ asset('default/css/magnific-popup.css') }}">

<link rel="stylesheet" type="text/css" href="{{ asset('default/css/font-awesome.min.css') }}">

<!-- ^ new --------------------------------------------- >
<!-- Bootstrap core CSS-->

<link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('bootstrap-v3.3.7/css/bootstrap.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/font-awesome.min.css') }}">

<!-- Custom fonts for this template-->
<link href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
<!-- Page level plugin CSS-->
<link href="{{ asset('vendor/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet">
<!-- Custom styles for this template-->
<link href="{{ asset('css/style.css') }}" rel="stylesheet">
<!-- Include Bootstrap Datepicker -->
<link rel="stylesheet" href="{{ asset('css/datepicker.min.css') }}" />
<link rel="stylesheet" href="{{ asset('css/datepicker3.min.css') }}" />

@yield('styles')
<style>
p {
    font-size: 20px;
}
</style>
<!-- new - sub Header topBar ---------------------------------- >

<!-- Header -->

<header class="header" id="site-header">

	<div class="page-title">
		<h6 id="site-header-title">Collabs @yield('title')</h6>
	</div>

	<div class="header-content-wrapper">

		<div class="control-block">

      <!-- Chat Messages Notification Block Element -->
			<div class="control-icon more has-items">
				<svg class="olymp-chat---messages-icon"><use xlink:href="{{ asset('default/icons') }}/icons.svg#olymp-chat---messages-icon"></use></svg>

				<div class="more-dropdown more-with-triangle triangle-top-center">
					<div class="mCustomScrollbar" data-mcs-theme="dark">
						<ul class="notification-list chat-message">

						</ul>
					</div>

					<a href="{{ route('message') }}" class="view-all bg-purple">View All Messages</a>
				</div>
			</div>
			<!-- end Chat Messages Notification Block Element -->

			<!-- Profile Button -->
			<div class="author-page author vcard inline-items more">
				<div class="author-thumb">
					<!-- Current User Image | eita silo > author-page.jpg -->
					<img alt="author" src="{{ asset('default/img') }}/fahim-pro-pic.png" class="avatar" style="width: 36px; height: 36px;">
					<span class="icon-status online"></span>
					<div class="more-dropdown more-with-triangle">
						<div class="ui-block-title ui-block-title-small">
							<h6 class="title">Your Account</h6>
						</div>

            <ul class="account-settings">
							<li>
								@if(session('is_user'))<a href="{{ route('profile.index')}}">
                @else <a href="{{ route('companyprofile.index')}}">
                @endif

									<svg class="olymp-menu-icon"><use xlink:href="{{ asset('default/icons') }}/icons.svg#olymp-menu-icon"></use></svg>

									<span>Profile Settings</span>
								</a>
							</li>
							<li>
								<a href="#">
									<svg class="olymp-happy-face-icon left-menu-icon"><use xlink:href="{{ asset('default/icons') }}/icons.svg#olymp-happy-face-icon"></use></svg>

									<span>Update Profile</span>
								</a>
							</li>
							<li>
								<a href="{{ route('logout') }}">
									<svg class="olymp-logout-icon"><use xlink:href="{{ asset('default/icons') }}/icons.svg#olymp-logout-icon"></use></svg>

									<span>Log Out</span>
								</a>
							</li>
						</ul>





						<div class="ui-block-title ui-block-title-small">
							<h6 class="title">About Collabs</h6>
						</div>

						<ul>
							<li>
								<a href="#">
									<span>Terms and Conditions</span>
								</a>
							</li>
							<li>
								<a href="#">
									<span>About</span>
								</a>
							</li>
							<li>
								<a href="#">
									<span>Careers</span>
								</a>
							</li>
							<li>
								<a href="#">
									<span>Reviews</span>
								</a>
							</li>
							<li>
								<a href="#">
									<span>Statistics</span>
								</a>
							</li>
						</ul>

					</div>
				</div>
				<a href="#" class="author-name fn">
					<div class="author-title">
						{{ (Session::has('username')) ? Session::get('username') : 'No Name' }} <svg class="olymp-dropdown-arrow-icon"><use xlink:href="{{ asset('default/icons') }}/icons.svg#olymp-dropdown-arrow-icon"></use></svg>
					</div>
					<span class="author-subtitle">{{ Session::get('is_user')? 'Developer' : 'Organization' }}</span>
				</a>
			</div>

		</div>
	</div>

</header>

<!-- ... end Header -->

<!-- ^newEnd ---------------------------------------------------->


</head>

<body>
  @yield('options')

  <!-- new ------------------------------------------------------>

  <div class="header-spacer"></div>


  <div class="container">


  		<!-- Main Content -->


        @include('alerts')

        @yield('content')

  </div>




  <!-- ^newEnd -------------------------------------------------->












  <!-- jQuery first, then Other JS. -->
  <script src="{{ asset('default/js/jquery-3.2.0.min.js') }}"></script>

  <!-- Lightbox popup script-->
  <script src="{{ asset('default/js/jquery.magnific-popup.min.js') }}"></script>

  <!-- Swiper / Sliders -->
  <script src="{{ asset('default/js/swiper.jquery.min.js') }}"></script>

  <!-- Js effects for material design. + Tooltips -->
  <script src="{{ asset('default/js/material.min.js') }}"></script>
  <!-- Helper scripts (Tabs, Equal height, Scrollbar, etc) -->
  <script src="{{ asset('default/js/theme-plugins.js') }}"></script>
  <!-- Init functions -->
  <script src="{{ asset('default/js/main.js') }}"></script>

  <!-- Load more news AJAX script -->
  <script src="{{ asset('default/js/ajax-pagination.js') }}"></script>

  <!-- Select / Sorting script -->
  <script src="{{ asset('default/js/selectize.min.js') }}"></script>

  <!-- Datepicker input field script-->
  <script src="{{ asset('default/js/moment.min.js') }}"></script>
  <script src="{{ asset('default/js/daterangepicker.min.js') }}"></script>

  <script src="{{ asset('default/js/mediaelement-and-player.min.js') }}"></script>
  <script src="{{ asset('default/js/mediaelement-playlist-plugin.min.js') }}"></script>

  <script src="{{ asset('default/js/menu.js') }}"></script>



  <!-- ^ new --------------------------------------------- >
  <!-- Bootstrap core JavaScript-->

<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- Core plugin JavaScript-->
<script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>
<!-- Page level plugin JavaScript-->
<script src="{{ asset('vendor/chart.js/Chart.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.js') }}"></script>
<!-- Custom scripts for all pages-->
<script src="{{ asset('js/sb-admin.min.js') }}"></script>
<!-- Custom scripts for this page-->
<script src="{{ asset('js/sb-admin-datatables.min.js') }}"></script>
<!--<script src="{{ asset('js/sb-admin-charts.min.js') }}"></script>-->
<script src="{{ asset('js/sb-admin-charts.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script>

<script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>

  @yield('page-scripts')
</body>

</html>

resources/views/register.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Register</title>
	<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
</head>
<body>
	<table border="0" width="100%">
		<tr>
			<td width="100"></td>
			<td align="center">
				<h1>Registration</h1>
			</td>
			<td width="100"></td>
		</tr>
		<tr>
			<td width="100"></td>
			<td align="center">
				<hr/>
			</td>
			<td width="100"></td>
		</tr>
		<tr>
			<td width="100"></td>
			<td>
				<br/>
				<br>
				<center>
					<div class="panel panel-default" style="background-color:#343A40;"><br><br>
	  <div class="panel-body">
				<form method="post">
					{{csrf_field()}}
						<table>
							<tr>
								<td></td>
								<td>
									<div class="input-group">
								    <span class="input-group-addon"><label style="margin-right:29px">Name:</label></span>
								    <input type="text" class="form-control" name="name" value="{{ old('name') }}">
								  </div>
							</tr>
							<tr>
								<td></td>
								<td>
									<div class="input-group">
								    <span class="input-group-addon"><label style="margin-right:29px">Email:</label></span>
								    <input type="text" class="form-control" name="email" value="{{ old('email') }}">
								  </div>
							</tr>
							<tr>
								<td></td>
								<td>
									<div class="input-group">
								    <span class="input-group-addon"><label>Password:</label></span>
								    <input type="password" class="form-control" name="password">
								  </div>
							</tr>
							<tr>
								<td></td>
								<td>
									<div class="input-group">
								    <span class="input-group-addon"><label style="font-size:11px">Re-Password</label></span>
								    <input type="password" class="form-control" name="repassword">
								  </div>
							</tr>

              <tr>
								<td></td>
								<td>
									<div class="input-group">
								    <span class="input-group-addon"><label>User Type:</label></span>
										<select class="form-control" name="type">
	                    <option value="0">Developer</option>
	                    <option value="1">Company</option>
	                  </select>
								  </div>

              </td>
							</tr>
							<tr>
								<td></td>
								<td><br><center><input type="submit" class="btn btn-success" value="Register"></center></td>
							</tr>
							<tr>
								<td></td>
								<td>
									<br><label style="margin-left:10px">Already A Member? Click <a href="{{route('login')}}">here</a> to login</label>
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
					<br/>
					<br/>
					<label>
						@if($errors->any())
						@foreach($errors->all() as $err)
						<p>{{$err}}</p>
						@endforeach
						@endif
					</label>
				</center>
			</td>
			<td width="100"></td>
		</tr>
	</table>
</body>
</html>
<style>
body{
	background-color:#343A40;
	color:white;
}
</style>