routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', 'LoginController@logout')->name('logout');
Route::get('/register', 'RegisterController@index')->name('register');
Route::post('/register', 'RegisterController@store')->name('register.execute');

Route::group(['middleware' => 'access.guest'], function(){
  Route::get('/login', 'LoginController@index')->name('login');
  Route::post('/login', 'LoginController@verify')->name('login.verify');
});

Route::group(['middleware' => 'access.auth'], function(){
  Route::get('teams/details/{id}', 'User\TeamController@details')->name('team.details.company');
  Route::get('profileOf/{id}', 'UserController@profile')->name('profileof.view');
  Route::get('contest/{id}', 'Company\ContestController@show_public')->name('contest.public.details');
  Route::get('message/{id}', 'UserController@getMessage')->name('messageOf');
  Route::post('message/{id}', 'UserController@sendMessage')->name('messageOf');

  Route::get('messages', 'UserController@messages')->name('message');

  Route::get('browse/users', 'CommonController@browse_users')->name('browse.users');
  Route::post('browse/users', 'CommonController@search_users')->name('browse.users.search');
  Route::get('browse/teams', 'CommonController@browse_teams')->name('browse.teams');
  Route::post('browse/teams', 'CommonController@search_teams')->name('browse.teams.search');
  Route::get('browse/contests', 'CommonController@browse_contests')->name('browse.contests');
  Route::post('browse/contests', 'CommonController@search_contests')->name('browse.contests.search');


  Route::group(['prefix' => 'user', 'middleware' => 'access.user'], function(){
    Route::get('/', 'User\HomeController@index')->name('user.home');

    Route::resource('profile', 'User\ProfileController', ['except' => 'show']);
    Route::get('profile/change/password', 'User\ProfileController@showchangepass')->name('user.pass.change');
    Route::post('profile/change/password', 'User\ProfileController@changepass')->name('user.pass.changing');
    Route::resource('projects', 'User\ProjectController');

    Route::get('contests', 'User\ContestController@index')->name('user.contests.index');
    Route::post('contests/join', 'User\ContestController@join')->name('user.contests.join');
    Route::post('contests', 'User\ContestController@participate')->name('user.contests.participate');
    Route::delete('contests/cancel', 'User\ContestController@cancel')->name('user.contests.cancel');

    Route::get('teams', 'User\TeamController@index')->name('team');

    Route::get('teams/create', 'User\TeamController@create')->name('team.create');
    Route::post('teams/create', 'User\TeamController@store')->name('team.store');

    Route::get('teams/edit/{id}', 'User\TeamController@edit')->name('team.edit');
    Route::post('teams/edit/{id}', 'User\TeamController@update')->name('team.update');

    Route::get('teams/details/{id}', 'User\TeamController@details')->name('team.details');

    Route::get('teams/searchuser/{id}', 'User\TeamController@searchuser')->name('team.searchuser');
    Route::post('teams/searchuser/{id}', 'User\TeamController@searchresult')->name('team.searchresult');

    Route::get('projects/searchteam/{id}', 'User\ProjectController@searchteam')->name('project.searchteam');
    Route::post('projects/searchteam/{id}', 'User\ProjectController@searchresult')->name('project.searchteam');
    Route::get('projects/leave/{id}/{lid}','User\ProjectController@pro_leave')->name('project.leave');

    Route::get('teams/invite/{teamid}/{userid}', 'User\TeamController@invite')->name('team.invite');
    Route::get('project/invite/{projectid}/{teamid}', 'User\ProjectController@invite')->name('project.invite');

    Route::get('teams/requests', 'User\TeamController@requests')->name('team.requests');
    Route::get('project/requests', 'User\ProjectController@requests')->name('project.requests');

    Route::get('project/decline/{id}', 'User\ProjectController@reqdecline')->name('project.decline');
    Route::get('project/accept/{id}', 'User\ProjectController@reqaccept')->name('project.accept');


    Route::get('teams/accept/{id}', 'User\TeamController@reqaccept')->name('team.accept');
    Route::get('teams/decline/{id}', 'User\TeamController@reqdecline')->name('team.decline');

    Route::get('teams/reqcancel/{teamid}/{userid}', 'User\TeamController@cancel')->name('team.reqcancel');
    Route::get('teams/memremove/{teamid}/{userid}', 'User\TeamController@memremove')->name('team.memremove');

    Route::get('project/requests/details/{projectid}/{teamid}/{userid}', 'User\ProjectController@reqdetails')->name('project.reqdetails');


    Route::get('offers', 'User\OfferController@index')->name('offers');
    Route::get('offers/accept/{id}', 'User\OfferController@accept')->name('offers.accept');
    Route::get('offers/decline/{id}', 'User\OfferController@decline')->name('offers.decline');
    Route::get('offers/details/{id}', 'User\OfferController@companydetails')->name('offers.companydetails');
  });

  Route::group(['prefix' => 'company', 'middleware' => 'access.company'], function(){
    Route::get('/', 'Company\HomeController@index')->name('company.home');

    Route::resource('companyprofile', 'Company\ProfileController', ['except' => 'show']);

    Route::resource('contests', 'Company\ContestController');
    Route::post('contests/request', 'Company\ContestController@request')->name('contests.request');

    Route::get('contests/invitations/list', 'Company\ContestController@show_invitation_list')->name('company.invitations.list');

    Route::post('contests/invitations/accept', 'Company\ContestController@invitation_accept')->name('company.invitations.accept');
    Route::post('contests/invitations/reject', 'Company\ContestController@invitation_reject')->name('company.invitations.reject');

    Route::post('contests/find/company', 'UserController@search_companies_by_name')->name('companies.find.by.name');

    Route::get('contests/{contest_id}/companies/invite', 'Company\ContestController@new_invite')->name('company.new.invite');
    Route::post('contests/companies/invite', 'Company\ContestController@request_invite')->name('company.request.invite');




    Route::get('review/{participant_id}/project/{project_id}/', 'Company\ReviewController@show')->name('company.review.show');
    Route::post('review/declare', 'Company\ReviewController@declare')->name('company.review.declare');
    Route::post('review/reject', 'Company\ReviewController@reject')->name('company.review.reject');

    Route::get('hires', 'Company\HireController@index')->name('hire.index');
    Route::post('hires', 'Company\HireController@searchresult')->name('hire.searchresult');
    Route::get('hires/userdetails/{id}', 'Company\HireController@userdetails')->name('userdetails');
    Route::post('hires/invite/', 'Company\HireController@hire')->name('hire.invite');
    Route::get('hires/invitations', 'Company\HireController@invitelist')->name('invitations');

  });

});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    public function team(){
      return $this->has('App\Team');
    }
}

app/Http/Controllers/Company/ProfileController.php
<?php

namespace App\Http\Controllers\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

use App\Http\Requests\CompanyRequest;
use Session;
class ProfileController extends Controller
{
    /*ki?
    //store hoy na. ei error
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $companydetails = DB::table('companydetails')
                      ->where('companyId',Session::get('id'))
                      ->first();




      if(!$companydetails){
        $company = DB::table('users')
                        ->where('id',Session::get('id'))
                        ->first();
        Session::put('menu', 'profile');
        return view('company.profile.profile')->with('company',$company);

      }

      $company = DB::table('users')
        ->join('companydetails', 'users.id', '=', 'companydetails.companyId')
        ->where('users.id', Session::get('id'))
        ->first();



//aeta to ager cntroooer er :3 ar  db- _te -___-t_______o- join nai..
      Session::put('menu', 'profile');
      return view('company.profile.profile')->with('company', $company);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
      $id =DB::table('companydetails')->insertGetId(
              ['companyId' => $request->session()->get('id'),
              'city' => $request->input('city'),
              'contactNo'=>$request->input('contactNo'),
              'website'=>$request->input('website'),
              'about'=>$request->input('about')
            ]
          );

          Session::flash('success', 'Your profile is Successfully saved !');
          return redirect()->route('company.home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //ae view te ashtse koi tidy_diagnose. index diye
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request)
    {
      $updateCompany=array(
              'companyId' => Session::get('id'),
              'city' => $request->input('city'),
              'contactNo' => $request->input('contactNo'),
              'website' => $request->input('website'),
              'about' => $request->input('about')

          );

    DB::table('companydetails')
          ->where('id', $request->input('id'))
          ->update($updateCompany);

      Session::flash('success', 'Your profile is Successfully updated !');
      return redirect()->route('companyprofile.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/ContestController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Contest;
use App\Team;
use App\Project;
use App\RelContestUser;
use Session;

class ContestController extends Controller
{
    public function index(){
      $contests = Contest::all();
      $teams = Team::where('leader_id', Session::get('id'))->get(['id', 'name']);

      $participations = RelContestUser::where('user_id', Session::get('id'))->get(['id', 'contest_id', 'team_id', 'project_id', 'status']);

      $data_array = array();
      $data_has = false;

      if(!$participations->isEmpty()){
        $data_has = true;

        foreach ($participations as $participation) {
          $data_array[] = [
            'id' => $participation->id,
            'contest_name' => Contest::where('id', $participation->contest_id)->first()['title'],
            'team_name' => Team::where('id', $participation->team_id)->first()['name'],
            'project_name' => Project::where('id', $participation->project_id)->first()['name'],
            'status' => $participation->status,
          ];
        }
      }

      Session::put('menu', 'contest');
      return view('user.contests.index')->with('contests', $contests)->with('teams', $teams)->with('joined_contests', $data_array)->with('has_data', $data_has);
    }

    public function join(Request $request){
      $check = RelContestUser::where('contest_id', $request->id)->where('team_id', $request->team)->exists();

      if(!$check){
        $projects = Project::where('team_id', $request->team)->get(['id', 'name']);

        return view('user.contests.join')->with('projects', $projects)->with('contest_id', $request->id)->with('team_id', $request->team);
      }

      Session::flash('fail', 'Your have already submitted for the Contest !');
      return redirect()->route('user.contests.index');
    }

    public function participate(Request $request){

      $this->validate($request, [
        'about' => 'nullable|max:500'
        ]);

      $contest_user = new RelContestUser;

      $contest_user->user_id = Session::get('id');
      $contest_user->contest_id = $request->contest_id;
      $contest_user->team_id = $request->team_id;
      $contest_user->project_id = $request->project_id;
      $contest_user->about = $request->about;

      $contest_user->save();

      Session::flash('success', 'Your Participation From is Successfully Submitted !');
      return redirect()->route('user.contests.index');
    }

    public function cancel(Request $request){
      RelContestUser::destroy($request->id);

      Session::flash('success', 'Your Participation is Successfully Cancelled !');
      return redirect()->route('user.contests.index');
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Session;
use App\User;
use App\Team;
use App\Project;
use App\Contest;
use App\RelContestUser;

class HomeController extends Controller
{

    public function index()
    {
      $users_count = $this->get_total_users();
      $teams_count = $this->get_total_teams();
      $projects_count = $this->get_total_projects();
      $contests_count = $this->get_total_contests();

      $winners = $this->get_winners();

      Session::put('menu', 'home');
      return view('user.home')
        ->with('users_count', $users_count)
        ->with('teams_count', $teams_count)
        ->with('projects_count', $projects_count)
        ->with('contests_count', $contests_count)
        ->with('winners', $winners);
    }

    private function get_total_users(){
      $users = User::all(['email']);

      if($users){
        return count($users);
      }
      return 0;
    }

    private function get_total_teams(){
      $teams = Team::all(['name']);

      if($teams){
        return count($teams);
      }
      return 0;
    }

    private function get_total_projects(){
      $projects = Project::all(['name']);

      if($projects){
        return count($projects);
      }
      return 0;
    }

    private function get_total_contests(){
      $contests = Contest::all(['title']);

      if($contests){
        return count($contests);
      }
      return 0;
    }

    public function get_winners(){
      $winning_participations = RelContestUser::where('status', 1)->get(['contest_id', 'team_id']);

      $winning_array = array();

      if(!$winning_participations->isEmpty()){
        foreach ($winning_participations as $winners) {
          $winning_array[] = [
            'contest_name' => Contest::where('id', $winners->contest_id)->first()['title'],
            'team_name' => Team::where('id', $winners->team_id)->first()['name'],
          ];
        }

        return $winning_array;
      }

      return null;
    }
}

resources/views/user/profile/changepass.blade.php
@extends ('user.layouts.options')

@section('title', ' | Developer Profile')

@section('content')
<a href="{{ URL::previous() }}" class="btn btn-primary">Back</a><br><br>

<div class="panel panel-info">
		<div class="panel-heading"><center>Change Password</center></div>
		<div class="panel-body">
					<form method ="POST" >
					{{ csrf_field() }}
          <input type="hidden" name="id" value="{{ Session::get('id') }}">
          <label>New Password</label>
          <input type="password" name="pass" />
          <br>
          <label>Confirm Password</label>
          <input type="password" name="conpass" />
          <input type="submit" name="change" />
          </form>
</div>
</div>
@endsection

resources/views/user/profile/create.blade.php
@extends ('user.layouts.options')

@section('title', ' | Developer Profile')

@section('content')
<div class="container-fluid">
  <div class="panel panel-default">
    <div class="panel-heading"><center><h4>{{session('username')}}</center></h4>

    </div>
  </div>
  <form method = "POST" action = "{{ route('profile.store') }}">
    {{ csrf_field() }}
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
        <div class="pull-left">
          <button type="submit" class="btn btn-success">Create Profile Info</button>
        </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">Personal Information

        </div>
        <div class="panel-body">
          <table class="table">
            <tr>
            <th>About Me:</th>
            <td><textarea name="aboutMe">{{ old('aboutMe') }}</textarea></td>
            </tr>
            <tr>
            <th>Date of Birth:</th>
            <td><input type="date" name="dOB" value="{{old('dateOfBirth')}}" /></td>
            </tr>
            <tr>
            <th>Lives in:</th>
            <td><input type="text" name="city" value="{{old('city')}}" /></td>
            </tr>
            <tr>
            <th>Occupation:</th>
            <td><input type="text" name="occupation" value="{{old('occupation')}}" /></td>
            </tr>
            <tr>
            <th>Gender:</th>
            <td>
              <select class="form-control" style='font-size: 10px;' name="gender">
                <option value="1">Female</option>
                <option value="2">Male</option>
              </select>
            </td>
            </tr>
            <tr>
            <th>Email:</th>
            <td>{{session('email')}}</td>
            </tr>
            <tr>
            <th>Website:</th>
            <td><input type="text" name="website" value="{{old('website')}}" /></td>
            </tr>
            <th>Contact No:</th>
            <td><input type="text" name="contactNo" value="{{old('contactNo')}}" /></td>
            </tr>
            <tr>

          </table>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">Skills</div>
        <div class="panel-body">
          <table class="table">
            <tr>
            <th>Programming Languages: (seperate with comma)</th>
            <td><input type="text" name="programing_languages" value="{{old('programming_language')}}" /></td>
            </tr>
            <tr>
            <th>Architectures, Patters & Frameworks:</th>
            <td><input type="text" name="archi" value="" /></td>
            </tr>
            <tr>
            <th>Project Experience:</th>
            <td><input type="text" name="projects" value="" /></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</form>
</div>

<!--modal maira de ekhane for EDIT CREATE er jnno alada page lagbe..validation shoho korbi -_- -->
@endsection

resources/views/user/profile/profile.blade.php
@extends ('user.layouts.options')

@section('title', ' | Developer Profile')

@section('content')
<a href="{{ route('user.pass.change') }}" class="btn btn-primary">Change Password</a>
<div class="panel panel-info">
		<div class="panel-heading"><center>Profile</center></div>
		<div class="panel-body">
@if(!isset($user->userId))
					<form method ="POST" action = "{{ route('profile.store') }}" >
					{{ csrf_field() }}
					<table class="table table-striped">
					<tr>
							<td style='width:20%; font-weight: bold;'>Name: </td>
							<td>{{ $user->name}}</td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>EMAIL: </td>
							<td>{{ $user->email }}</td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>TYPE: </td>
							@if ($user->type == 0)
							<td>Developer</td>
							@else
							<td>Company</td>
							@endif
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>DATE OF BIRTH: </td>
									<td>
										<div class="input-group input-append date" id="birth_dateRangePicker">
												<input type="text" class="form-control" name="dOB" value="{{ old('dOB') }}" />
												<span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
										</div>
									</td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>CITY: </td>
							<td><input type="text" class="form-control" name="city" value="{{ old('city') }}"></td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>GENDER: </td>
									<td><select class="form-control" style='font-size: 10px;'name="gender" value="{{ old('gender') }}">
											<option value="1">MALE</option>
											<option value="2">FEMALE</option>
											<option value="3">OTHERS</option>
									</select></td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>CONTACT NO: </td>
							<td><input type="text" class="form-control" name="contactNo" value="{{ old('contactNo') }}"></td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>OCCUPATION: </td>
							<td><input type="text" class="form-control" name="occupation" value="{{ old('occupation') }}"></td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>WEBSITE: </td>
							<td><input type="text" class="form-control" name="website" value="{{ old('website') }}"></td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>ABOUT ME: </td>
							<td>
									<textarea name="aboutMe" class="form-control" >{{ old('aboutMe') }}</textarea>
							</td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>PAST EXPERIENCE: </td>
							<td><input type="text" class="form-control" name="pastExperience" value="{{ old('pastExperience') }}"></td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>EDUCATION: </td>
							<td><input type="text" class="form-control" name="education" value="{{ old('education') }}"></td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>PROGRAMMING EXPERIENCE: </td>
							<td><input type="text" class="form-control" name="programmingExperience" value="{{ old('programmingExperience') }}"></td>
					</tr>
					<tr>
							<td style='width:20%; font-weight: bold;'>PROJECTS: </td>
							<td><input type="text" class="form-control" name="projects" value="{{ old('projects') }}"></td>
					</tr>
    			</table>
					<input type="submit" class="btn btn-warning" value="Update">


					</form>
@else
					<form method ="POST" action = "{{ route('profile.update', [$user->id]) }}" >
					<input type="hidden" name="_method" value="put" />
					<input type="hidden" name="id" value="{{ $user->id }}" />
					{{ csrf_field() }}

					<table class="table table-striped">
					<tr>
						<td style='width:20%; font-weight: bold;'>Name: </td>
						<td>{{ $user->name}}</td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>EMAIL: </td>
						<td>{{ $user->email }}</td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>TYPE: </td>
						@if ($user->type == 0)
						<td>Developer</td>
						@else
						<td>Company</td>
						@endif
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>DATE OF BIRTH: </td>
								<td>{{ \Carbon\Carbon::parse($user->dateOfBirth)->format('d/m/Y') }}</td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>CITY: </td>
						<td><input type="text" class="form-control" name="city" value="{{$user->city}}"></td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>GENDER: </td>
									@if($user->gender == 0)
									<td>Male</td>
									@elseif($user->gender == 1)
									<td>Female</td>
									@else
									<td>Others</td>
									@endif
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>CONTACT NO: </td>
						<td><input type="text" class="form-control" name="contactNo" value="{{$user->contactNo}}"></td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>OCCUPATION: </td>
						<td><input type="text" class="form-control" name="occupation" value="{{$user->occupation}}"></td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>WEBSITE: </td>
						<td><input type="text" class="form-control" name="website" value="{{$user->website}}"></td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>ABOUT ME: </td>
						<td>
								<textarea name="aboutMe">{{$user->aboutMe}}</textarea>
						</td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>PAST EXPERIENCE: </td>
						<td><input type="text" class="form-control" name="pastExperience" value="{{$user->pastExperience}}"></td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>EDUCATION: </td>
						<td><input type="text" class="form-control" name="education" value=""></td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>PROGRAMMING EXPERIENCE: </td>
						<td><input type="text" class="form-control" name="programmingExperience" value="{{$user->programmingExperience}}"></td>
					</tr>
					<tr>
						<td style='width:20%; font-weight: bold;'>PROJECTS: </td>
						<td><input type="text" class="form-control" name="projects" value="{{$user->projects}}"></td>
					</tr>

					</table>
					<input type="submit" class="btn btn-warning" value="Update">
					</form>
@endif
			</td>
		</tr>
	</table>
</div>
</div>
@endsection

@section('page-scripts')
  <script>
  $(document).ready(function() {
      $('#birth_dateRangePicker')
          .datepicker({
              format: 'dd/mm/yyyy',
              startDate: '01/01/1990',
              endDate: '30/12/2020'
          })
          .on('changeDate', function(e) {
              // Revalidate the date field
              $('#dateRangeForm').formValidation('revalidateField', 'date');
          });
  });
  </script>
@endsection

resources/views/user/profile/show.blade.php
@extends ('user.layouts.options')

@section('title', ' | Developer Profile')

@section('content')
<div class="container-fluid">
  <div class="panel panel-default">
    <div class="panel-heading"><center><h4>{{session('username')}}</center></h4>

    </div>
  </div>
  <div class="row">
    @if(!isset($nai))
    <div class="col-md-4">
      @if($main_user->id === session('id'))
        <div class="panel panel-default">
          <div class="panel-body">
          <div class="pull-left">
            <a href="{{ route('profile.edit', [$user->id]) }}"><button type="button" class="btn btn-warning">Edit Your Profile</button></a>
          </div>
          </div>
        </div>
      @endif
    <div class="panel panel-default">
      <div class="panel-heading">Personal Information

      </div>
      <div class="panel-body">
        <table class="table">
          <tr>
          <th>About Me:</th>
          <td>{{$user->aboutMe}}</td>
          </tr>
          <tr>
          <th>Date of Birth:</th>
          <td>{{$user->dateOfBirth}}&nbsp;({{$age}})</td>
          </tr>
          <tr>
          <th>Lives in:</th>
          <td>{{$user->city}}</td>
          </tr>
          <tr>
          <th>Occupation:</th>
          <td>{{$user->occupation}}</td>
          </tr>
          <tr>
          <th>Joined:</th>
          <td>{{ $joined_when }}</td>
          </tr>
          <tr>
          <th>Gender:</th>
          @if($user->gender == 0)
          <td>Male</td>
          @elseif($user->gender == 1)
          <td>Female</td>
          @else
          <td>Others</td>
          @endif
          </tr>
          <tr>
          <th>Email:</th>
          <td>{{session('email')}}</td>
          </tr>
          <tr>
          <th>Website:</th>
          <td><a href="{{$user->website}}">{{$user->website}}</a></td>
          </tr>
          <th>Contact No:</th>
          <td>{{$user->contactNo}}</td>
          </tr>
          <tr>

        </table>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">Skills</div>
      <div class="panel-body">
        <table class="table">
          <tr>
          <th>Programming Languages:</th>
          <td>{{$user->programming_language}}</td>
          </tr>
          <tr>
          <th>Architectures, Patters & Frameworks:</th>
          <td>{{$user->archi_patters}}</td>
          </tr>
          <tr>
          <th>Project Experience:</th>
          <td>{{$user->projects}}</td>
          </tr>
          <tr>
          <th>Completed Project:</th>
          <td>{{$done}}</td>
          </tr>
        </table>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Education and Employement</div>
      <div class="panel-body">
        <div class="well well-sm">Education:</div>
        <div class="row">
        @foreach($edu as $ed)
        <div class="col-md-6">
          <label>{{$ed->institution_name}}</label>
          <p style="font-size:14px;">{{$ed->department}}</p>
          <p style="font-size:11px;">({{$ed->start}})-({{$ed->end}})</p>
        </div>
        @endforeach
      </div>
        <div class="well well-sm">Employement:</div>
        <div class="row">
        @foreach($job as $ed)
        <div class="col-md-6">
          <label>{{$ed->institution_name}}</label>
          <p style="font-size:14px;">{{$ed->department}}</p>
          <p style="font-size:11px;">({{$ed->start}})-({{$ed->end}})</p>
        </div>
        @endforeach
        </div>
      </div>
    </div>
  </div>
  @else
  <div class="col-md-6">
    Profile not created Yet!
  </div>
  <div class="col-md-6">
    <div class="pull-right">
      <a href="{{ route('profile.create') }}" class="btn btn-primary">Create<a>
    </div>
  </div>
  @endif
  </div>
</div>

<!--modal maira de ekhane for EDIT CREATE er jnno alada page lagbe..validation shoho korbi -_- -->
@endsection