routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', 'LoginController@logout')->name('logout');
Route::get('/register', 'RegisterController@index')->name('register');
Route::post('/register', 'RegisterController@store')->name('register.execute');

Route::group(['middleware' => 'access.guest'], function(){
  Route::get('/login', 'LoginController@index')->name('login');
  Route::post('/login', 'LoginController@verify')->name('login.verify');
});

Route::group(['middleware' => 'access.auth'], function(){
  Route::get('teams/details/{id}', 'User\TeamController@details')->name('team.details.company');
  Route::get('profileOf/{id}', 'UserController@profile')->name('profileof.view');
  Route::get('contest/{id}', 'Company\ContestController@show_public')->name('contest.public.details');
  Route::get('message/{id}', 'UserController@getMessage')->name('messageOf');
  Route::post('message/{id}', 'UserController@sendMessage')->name('messageOf');

  Route::get('messages', 'UserController@messages')->name('message');

  Route::get('browse/users', 'CommonController@browse_users')->name('browse.users');
  Route::post('browse/users', 'CommonController@search_users')->name('browse.users.search');
  Route::get('browse/teams', 'CommonController@browse_teams')->name('browse.teams');
  Route::post('browse/teams', 'CommonController@search_teams')->name('browse.teams.search');
  Route::get('browse/contests', 'CommonController@browse_contests')->name('browse.contests');
  Route::post('browse/contests', 'CommonController@search_contests')->name('browse.contests.search');


  Route::group(['prefix' => 'user', 'middleware' => 'access.user'], function(){
    Route::get('/', 'User\HomeController@index')->name('user.home');

    Route::resource('profile', 'User\ProfileController', ['except' => 'show']);
    Route::get('profile/change/password', 'User\ProfileController@showchangepass')->name('user.pass.change');
    Route::post('profile/change/password', 'User\ProfileController@changepass')->name('user.pass.changing');
    Route::resource('projects', 'User\ProjectController');

    Route::get('contests', 'User\ContestController@index')->name('user.contests.index');
    Route::post('contests/join', 'User\ContestController@join')->name('user.contests.join');
    Route::post('contests', 'User\ContestController@participate')->name('user.contests.participate');
    Route::delete('contests/cancel', 'User\ContestController@cancel')->name('user.contests.cancel');

    Route::get('teams', 'User\TeamController@index')->name('team');

    Route::get('teams/create', 'User\TeamController@create')->name('team.create');
    Route::post('teams/create', 'User\TeamController@store')->name('team.store');

    Route::get('teams/edit/{id}', 'User\TeamController@edit')->name('team.edit');
    Route::post('teams/edit/{id}', 'User\TeamController@update')->name('team.update');

    Route::get('teams/details/{id}', 'User\TeamController@details')->name('team.details');

    Route::get('teams/searchuser/{id}', 'User\TeamController@searchuser')->name('team.searchuser');
    Route::post('teams/searchuser/{id}', 'User\TeamController@searchresult')->name('team.searchresult');

    Route::get('projects/searchteam/{id}', 'User\ProjectController@searchteam')->name('project.searchteam');
    Route::post('projects/searchteam/{id}', 'User\ProjectController@searchresult')->name('project.searchteam');
    Route::get('projects/leave/{id}/{lid}','User\ProjectController@pro_leave')->name('project.leave');

    Route::get('teams/invite/{teamid}/{userid}', 'User\TeamController@invite')->name('team.invite');
    Route::get('project/invite/{projectid}/{teamid}', 'User\ProjectController@invite')->name('project.invite');

    Route::get('teams/requests', 'User\TeamController@requests')->name('team.requests');
    Route::get('project/requests', 'User\ProjectController@requests')->name('project.requests');

    Route::get('project/decline/{id}', 'User\ProjectController@reqdecline')->name('project.decline');
    Route::get('project/accept/{id}', 'User\ProjectController@reqaccept')->name('project.accept');


    Route::get('teams/accept/{id}', 'User\TeamController@reqaccept')->name('team.accept');
    Route::get('teams/decline/{id}', 'User\TeamController@reqdecline')->name('team.decline');

    Route::get('teams/reqcancel/{teamid}/{userid}', 'User\TeamController@cancel')->name('team.reqcancel');
    Route::get('teams/memremove/{teamid}/{userid}', 'User\TeamController@memremove')->name('team.memremove');

    Route::get('project/requests/details/{projectid}/{teamid}/{userid}', 'User\ProjectController@reqdetails')->name('project.reqdetails');


    Route::get('offers', 'User\OfferController@index')->name('offers');
    Route::get('offers/accept/{id}', 'User\OfferController@accept')->name('offers.accept');
    Route::get('offers/decline/{id}', 'User\OfferController@decline')->name('offers.decline');
    Route::get('offers/details/{id}', 'User\OfferController@companydetails')->name('offers.companydetails');
  });

  Route::group(['prefix' => 'company', 'middleware' => 'access.company'], function(){
    Route::get('/', 'Company\HomeController@index')->name('company.home');

    Route::resource('companyprofile', 'Company\ProfileController', ['except' => 'show']);

    Route::resource('contests', 'Company\ContestController');
    Route::post('contests/request', 'Company\ContestController@request')->name('contests.request');

    Route::get('contests/invitations/list', 'Company\ContestController@show_invitation_list')->name('company.invitations.list');

    Route::post('contests/invitations/accept', 'Company\ContestController@invitation_accept')->name('company.invitations.accept');
    Route::post('contests/invitations/reject', 'Company\ContestController@invitation_reject')->name('company.invitations.reject');

    Route::post('contests/find/company', 'UserController@search_companies_by_name')->name('companies.find.by.name');

    Route::get('contests/{contest_id}/companies/invite', 'Company\ContestController@new_invite')->name('company.new.invite');
    Route::post('contests/companies/invite', 'Company\ContestController@request_invite')->name('company.request.invite');




    Route::get('review/{participant_id}/project/{project_id}/', 'Company\ReviewController@show')->name('company.review.show');
    Route::post('review/declare', 'Company\ReviewController@declare')->name('company.review.declare');
    Route::post('review/reject', 'Company\ReviewController@reject')->name('company.review.reject');

    Route::get('hires', 'Company\HireController@index')->name('hire.index');
    Route::post('hires', 'Company\HireController@searchresult')->name('hire.searchresult');
    Route::get('hires/userdetails/{id}', 'Company\HireController@userdetails')->name('userdetails');
    Route::post('hires/invite/', 'Company\HireController@hire')->name('hire.invite');
    Route::get('hires/invitations', 'Company\HireController@invitelist')->name('invitations');

  });

});

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
  public function projects(){
    return $this->hasMany('App\Project');
  }

  public function contests()
  {
      return $this->belongsToMany('App\Contest');
  }

  public function user(){
    return $this->belongsTo('App\User');
  }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    public function team(){
      return $this->has('App\Team');
    }
}

app/Http/Controllers/User/ContestController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Contest;
use App\Team;
use App\Project;
use App\RelContestUser;
use Session;

class ContestController extends Controller
{
    public function index(){
      $contests = Contest::all();
      $teams = Team::where('leader_id', Session::get('id'))->get(['id', 'name']);

      $participations = RelContestUser::where('user_id', Session::get('id'))->get(['id', 'contest_id', 'team_id', 'project_id', 'status']);

      $data_array = array();
      $data_has = false;

      if(!$participations->isEmpty()){
        $data_has = true;

        foreach ($participations as $participation) {
          $data_array[] = [
            'id' => $participation->id,
            'contest_name' => Contest::where('id', $participation->contest_id)->first()['title'],
            'team_name' => Team::where('id', $participation->team_id)->first()['name'],
            'project_name' => Project::where('id', $participation->project_id)->first()['name'],
            'status' => $participation->status,
          ];
        }
      }

      Session::put('menu', 'contest');
      return view('user.contests.index')->with('contests', $contests)->with('teams', $teams)->with('joined_contests', $data_array)->with('has_data', $data_has);
    }

    public function join(Request $request){
      $check = RelContestUser::where('contest_id', $request->id)->where('team_id', $request->team)->exists();

      if(!$check){
        $projects = Project::where('team_id', $request->team)->get(['id', 'name']);

        return view('user.contests.join')->with('projects', $projects)->with('contest_id', $request->id)->with('team_id', $request->team);
      }

      Session::flash('fail', 'Your have already submitted for the Contest !');
      return redirect()->route('user.contests.index');
    }

    public function participate(Request $request){

      $this->validate($request, [
        'about' => 'nullable|max:500'
        ]);

      $contest_user = new RelContestUser;

      $contest_user->user_id = Session::get('id');
      $contest_user->contest_id = $request->contest_id;
      $contest_user->team_id = $request->team_id;
      $contest_user->project_id = $request->project_id;
      $contest_user->about = $request->about;

      $contest_user->save();

      Session::flash('success', 'Your Participation From is Successfully Submitted !');
      return redirect()->route('user.contests.index');
    }

    public function cancel(Request $request){
      RelContestUser::destroy($request->id);

      Session::flash('success', 'Your Participation is Successfully Cancelled !');
      return redirect()->route('user.contests.index');
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Session;
use App\User;
use App\Team;
use App\Project;
use App\Contest;
use App\RelContestUser;

class HomeController extends Controller
{

    public function index()
    {
      $users_count = $this->get_total_users();
      $teams_count = $this->get_total_teams();
      $projects_count = $this->get_total_projects();
      $contests_count = $this->get_total_contests();

      $winners = $this->get_winners();

      Session::put('menu', 'home');
      return view('user.home')
        ->with('users_count', $users_count)
        ->with('teams_count', $teams_count)
        ->with('projects_count', $projects_count)
        ->with('contests_count', $contests_count)
        ->with('winners', $winners);
    }

    private function get_total_users(){
      $users = User::all(['email']);

      if($users){
        return count($users);
      }
      return 0;
    }

    private function get_total_teams(){
      $teams = Team::all(['name']);

      if($teams){
        return count($teams);
      }
      return 0;
    }

    private function get_total_projects(){
      $projects = Project::all(['name']);

      if($projects){
        return count($projects);
      }
      return 0;
    }

    private function get_total_contests(){
      $contests = Contest::all(['title']);

      if($contests){
        return count($contests);
      }
      return 0;
    }

    public function get_winners(){
      $winning_participations = RelContestUser::where('status', 1)->get(['contest_id', 'team_id']);

      $winning_array = array();

      if(!$winning_participations->isEmpty()){
        foreach ($winning_participations as $winners) {
          $winning_array[] = [
            'contest_name' => Contest::where('id', $winners->contest_id)->first()['title'],
            'team_name' => Team::where('id', $winners->team_id)->first()['name'],
          ];
        }

        return $winning_array;
      }

      return null;
    }
}

app/Http/Controllers/User/OfferController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Session;

class OfferController extends Controller
{
    //
    public function index(){
      $offers=DB::table('hire')
                ->join('users','users.id','=','hire.company_id')
                ->where('hire.user_id',session('id'))
                ->where('accept','<',4)
                ->get();

      $team_offers = DB::table('hire')
                        ->join('teams','teams.id','=','hire.user_id')
                        ->join('users','users.id','=','hire.company_id')
                        ->where([
                          ['hire.accept','>',3],
                          ['teams.leader_id',session('id')],
                        ])
                        ->select('hire.offer_id','hire.company_id','hire.user_id as team_id','hire.accept','hire.details','users.name as company_name','teams.name as team_name')
                        ->get();
      Session::put('menu', 'offers');
      return view('user.offer.index')->withOffers($offers)->withTeamoffers($team_offers);
    }

    public function companydetails($id){
      $company=DB::table('companydetails')
                ->join('users','users.id','=','companydetails.companyId')
                ->where('users.id',$id)
                ->first();
      return view('user.offer.companydetails')->withCompany($company);
    }

    public function accept($id){
      $get=DB::table('hire')->where('offer_id',$id)->first();
      if($get->accept==0){
      DB::table('hire')
          ->where('offer_id',$id)
          ->update(['accept'=>1]);
      }
      else{
      DB::table('hire')
          ->where('offer_id',$id)
          ->update(['accept'=>5]);

      }

    Session::flash('success', 'Offer Accepted!');
      return redirect()->route('offers');
    }
    public function decline($id){
      $get=DB::table('hire')->where('offer_id',$id)->first();
      if($get->accept==0){
      DB::table('hire')
          ->where('offer_id',$id)
          ->update(['accept'=>3]);
      }
      else{
      DB::table('hire')
          ->where('offer_id',$id)
          ->update(['accept'=>6]);

      }
    Session::flash('success', 'Offer Declined!');
      return redirect()->route('offers');
    }
}

resources/views/user/team/create.blade.php
@extends ('user.layouts.options')

@section('title', ' | Teams - Create')

@section('content')

<div class="container-fluid">
  <a href="{{ URL::previous() }}" class="btn btn-primary">Back</a><br><br>
  <div class="panel-group">
    <div class="panel panel-info">
        <div class="panel-heading">Create Team</div>
        <div class="panel-body">


          <form class="form-horizontal" method="post">
            {{csrf_field()}}
            <input type="hidden" name="leader_id" value="{{Session::get('id')}}" />
                 <div class="form-group">
                   <label class="control-label col-sm-2">Team Name:</label>
                   <div class="col-sm-10">
                     <input type="text" class="form-control" placeholder="Enter Team Name" name="team_name">
                   </div>
                 </div>
                 <div class="form-group">
                   <label class="control-label col-sm-2">Description:</label>
                   <div class="col-sm-10">
                     <textarea class="form-control" rows="5" placeholder="Team Description" name="description"></textarea>
                   </div>
                 </div>

                 <div class="form-group">
                   <label class="control-label col-sm-2">Total Member:</label>
                   <div class="col-sm-10">
                     <select class="form-control" name="total_member" style="font-size:10px;">
                       @for ($i = 1; $i < 51; $i++)
                           <option value="{{$i}}">{{$i}}</option>
                       @endfor
                     </select>

                   </div>
                 </div>

                 <div class="form-group">
                   <label class="col-sm-10 col-sm-offset-2">
                     @if($errors->any())
         						@foreach($errors->all() as $err)
         						<p>{{$err}}</p>
         						@endforeach
         						@endif
                  </label>
                 </div>
                 <div class="form-group">
                   <div class="col-sm-offset-2 col-sm-10">
                     <button type="submit" class="btn btn-primary">Submit</button>
                   </div>
                 </div>
                </form>






        </div>
      </div>
  </div>
</div>
@endsection

resources/views/user/team/details.blade.php
@extends(session('is_user')? 'user.layouts.options' : 'company.layouts.options')
@section('title', ' | Teams - Detail')

@section('content')
<div class="container-fluid">
  <a href="{{ URL::previous() }}" class="btn btn-primary">Back</a>
  <br />
  <br />
  <div class="panel panel-default">
    <div class="panel-heading">Description</div>
    <div class="panel-body">{{$leader->description}}</div>
  </div>
  <div class="row">
    <div class="col-md-6">
      @if($parbe==1)
      @if ($projects)
        <div class="card">
          <div class="card-body">
              <p class="lead">
                <strong>On Development Phase</strong>
              </p>
              @foreach ($projects as $project)
                @if ($project->status)
                  <div class="card">
                    <div class="card-body">
                        <p class="lead">
                          <i>{{ $project->name }}</i>
                        </p>
                        <p>{{ $project->details }}</p>
                        <div class="pull-right">
                          <a href="{{ route('projects.show', [$project->id]) }}" class="btn btn-sm btn-info">Project Details</a>
                        </div>
                    </div>
                  </div>
                @else
                  <div class="card">
                    <div class="card-body">
                        <p class="lead">
                          <i>No Projects Yet !</i>
                        </p>
                    </div>
                  </div>
                @endif
              @endforeach
          </div>
        </div>
        <div class="card">
          <div class="card-body">
              <p class="lead">
                <strong>Finished</strong>
              </p>
              @foreach ($projects as $project)
                @if (!$project->status)
                  <div class="card">
                    <div class="card-body">
                        <p class="lead">
                          <i>{{ $project->name }}</i>
                        </p>
                        <p>{{ $project->details }}</p>
                        <div class="pull-right">
                          <a href="{{ route('projects.show', [$project->id]) }}" class="btn btn-sm btn-info">Project Details</a>
                        </div>
                    </div>
                  </div>
                @else
                  <div class="card">
                    <div class="card-body">
                        <p class="lead">
                          <i>No Projects Yet !</i>
                        </p>
                    </div>
                  </div>
                @endif
              @endforeach
          </div>
        </div>
      @else
        <div class="card">
          <div class="card-body">
              <p class="lead">
                <strong>On Development Phase</strong>
              </p>
              <div class="card">
                <div class="card-body">
                    <p class="lead">
                      <i>No Projects Yet !</i>
                    </p>
                </div>
              </div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
              <p class="lead">
                <strong>Finished</strong>
              </p>
              <div class="card">
                <div class="card-body">
                    <p class="lead">
                      <i>No Projects Yet !</i>
                    </p>
                </div>
              </div>
          </div>
        </div>
      @endif
      @endif
      @if(session('is_company'))
      <div class="card">
        <div class="card-body">
            <p class="lead">
              <strong>  Invite to Hire:</strong>
            </p>
            <form method="POST" action="{{route('hire.invite')}}">
              {{ csrf_field() }}
              <input type="hidden" name="user_id" value="{{ $teamid }}" />
              <input type="hidden" name="who" value="team" />

              <div class="form-group">
           <label for="comment">Message:</label>
           <textarea class="form-control" rows="5" name="details"></textarea>
          </div>
            <button type="submit" class="btn btn-primary">Hire</button><br><br>
          </form>

        </div>
      </div>

      @endif
    </div>
    <div class="col-md-6">

      @if($leader->id == session('id'))
      <a href="{{route('team.searchuser',[$teamid])}}" class="btn btn-primary">Add User</a><br><br>
      @endif
      <div class="well well-sm border border-dark">Leader:</div>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading"><a href="{{route('profileof.view',[$leader->id])}}">{{$leader->name}}</a></h4>
          <p>{{$leader->email}}</p>
        </div>
      </div>
      <br>
      <div class="well well-sm border border-dark">Members:</div>
      @foreach($members as $mem)
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">{{$loop->iteration}}. {{$mem->name}}
          @if($mem->invite==0 && $leader->id==session('id'))
            (invited)
            <a href="{{route('team.reqcancel',[$teamid,$mem->id])}}" class="btn btn-danger pull-right">Cancel</a>
          @elseif($leader->id==session('id'))
          <a href="{{route('team.memremove',[$teamid,$mem->id])}}" class="btn btn-danger pull-right">Remove</a>
          @endif</h4>
          <p>{{$mem->email}}</p>
        </div>
      </div>
      @endforeach
    </div>

  </div>
</div>
@endsection

resources/views/user/team/edit.blade.php
@extends ('user.layouts.options')

@section('title', ' | Teams - Edit')

@section('content')
<div class="container-fluid">
  <a href="{{ URL::previous() }}" class="btn btn-primary">Back</a><br><br>
  <div class="panel-group">
    <div class="panel panel-info">
        <div class="panel-heading">EditTeam</div>
        <div class="panel-body">
          <form class="form-horizontal" method="post" action="{{ route('team.update', [$team->id]) }}">
            {{csrf_field()}}
            <input type="hidden" name="id" value="{{$team->id}}"/>
            <input type="hidden" name="old_name" value="{{$team->name}}"/>
            <input type="hidden" name="leader_id" value="{{Session::get('id')}}"/>
                 <div class="form-group">
                   <label class="control-label col-sm-2">Team Name:</label>
                   <div class="col-sm-10">
                     <input type="text" class="form-control" value="{{$team->name}}" name="team_name">
                   </div>
                 </div>
                 <div class="form-group">
                   <label class="control-label col-sm-2">Description:</label>
                   <div class="col-sm-10">
                     <textarea class="form-control" rows="5" name="description">{{$team->description}}</textarea>
                   </div>
                 </div>

                 <div class="form-group">
                   <label class="control-label col-sm-2">Total Member:</label>
                   <div class="col-sm-10">
                     <select class="form-control" name="total_member" style="font-size:10px;">
                       @for ($i = $team->existing_member; $i < 51; $i++)
                           <option value="{{$i}}" {{ ($i == $team->total_member) ? ' selected="selected"' : '' }}>{{$i}}</option>
                       @endfor
                     </select>

                   </div>
                 </div>
                 <div class="form-group">
                         <label class="control-label col-sm-2">Status</label>
                         <div class="col-sm-10">
                         <select name="status" class="form-control" style="font-size:10px;">
                           <option value="0" {{ ($team->status === 0) ? 'selected' : '' }}>Enable</option>
                           <option value="1" {{ ($team->status === 1) ? 'selected' : '' }}>Disband</option>
                         </select>
                       </div>
                 </div>
                 <div class="form-group">
                         <label class="control-label col-sm-2">Last Updated:</label>
                         <div class="col-sm-10">
                         {{$team->updated_at}}
                       </div>
                 </div>

                 <div class="form-group">
                   <label class="col-sm-10 col-sm-offset-2">
                     @if($errors->any())
         						@foreach($errors->all() as $err)
         						<p>{{$err}}</p>
         						@endforeach
         						@endif
                  </label>
                 </div>
                 <div class="form-group">
                   <div class="col-sm-offset-2 col-sm-10">
                     <button type="submit" class="btn btn-primary">Submit</button>
                   </div>
                 </div>
                </form>






        </div>
      </div>
  </div>
</div>
@endsection

resources/views/user/team/index.blade.php
@extends ('user.layouts.options')

@section('title', ' | Teams')

@section('content')
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <a href="{{route('team.create')}}" class="btn btn-primary">Create your Team</a>
  <a href="{{route('team.requests')}}" class="btn btn-warning pull-right">
    ({{$rqsts}})
    Team Requests</a><br><br>
  <div class="row">
    <div class="col-md-6">
      My Team:
      @foreach($myteam as $jin)
      @if($jin->status == 1)
        <div class="panel panel-default">
      @else
      <div class="panel panel-info">
      @endif
          <div class="panel-heading">
          <div class="row">
            <div class="col-md-4" style="font-size:20px;">
              <a href="{{route('team.details',[$jin->id])}}">{{$jin->name}}</a>
            </div>
          <div class="col-md-8">
          Members({{$jin->existing_member}}/{{$jin->total_member}})
          @if($jin->status==1)
            (Disbanded)
          @endif
          <a href="{{ route('team.edit', [$jin->id]) }}" class="btn btn-sm btn-warning pull-right">Edit</a>
        </div>
        </div>
      </div>
          <div class="panel-body">
              {{$jin->description}}<br>
              -Leaded By: {{$jin->leader_name}}
          </div>
        </div>
      @endforeach
      {{ $myteam->links() }}

      </div>
  <div class="col-md-6">
    Joined Team:
    @foreach($joindteam as $jin)
    @if($jin->status == 1)
            <div class="panel panel-default">
        @else
          <div class="panel panel-info">
        @endif
              <div class="panel-heading">
                <div class="row">
                  <div class="col-md-4" style="font-size:20px;">
                  <a href="{{route('team.details',[$jin->id])}}">{{$jin->name}}</a>

                  </div>
                <div class="col-md-8">
              Members({{$jin->existing_member}}/{{$jin->total_member}})
              @if($jin->status==1)
                (Disbanded)
              @endif
              <a href="#" class="pull-right">Member</a>
              </div>
                </div>
              </div>
              <div class="panel-body">
                  {{$jin->description}}<br>
                  -Leaded By: {{$jin->leader_name}}
              </div>
            </div>
        @endforeach
        {{ $joindteam->links() }}

          </div>

  </div>

  </div>
</div>
@endsection

resources/views/user/team/requests.blade.php
@extends ('user.layouts.options')

@section('title', ' | Teams - Requests')

@section('content')
<div class="container-fluid">
<a href="{{ URL::previous() }}" class="btn btn-primary">Back</a><br><br>
  @if($has!=0)
  @foreach($teams as $jin)
    <div class="panel panel-default">
      <div class="panel-heading">
      <div class="row">
        <div class="col-md-2" style="font-size:20px;">
          <a href="{{route('team.details',[$jin->id])}}">{{$jin->name}}</a>
        </div>
      <div class="col-md-10">
      Members({{$jin->existing_member}}/{{$jin->total_member}})
      @if($jin->status==1)
        (Disbanded)
      @endif
      <a href="{{ route('team.decline', [$jin->id]) }}" class="btn btn-sm btn-danger pull-right">Decline</a>
      <a href="{{ route('team.accept', [$jin->id]) }}" class="btn btn-sm btn-warning pull-right">Accept</a>
    </div>
    </div>
  </div>
      <div class="panel-body">
          {{$jin->description}}<br>
          -Leaded By: {{$jin->leader_name}}
      </div>
    </div>
  @endforeach
  {{ $teams->links() }}
  @else
  No Requests To Show
  @endif
    </div>
@endsection

resources/views/user/team/searchresult.blade.php
@extends ('user.layouts.options')

@section('title', ' | Teams - Search Results')

@section('content')
<a href="{{ URL::previous() }}" class="btn btn-primary">Back</a><br><br>
@if(count($users)==0)
No search Result
@endif
@foreach($users as $us)
<div class="panel panel-default">
  <div class="panel-heading"><a href="{{route('profileof.view',[$us->id])}}">{{$us->name}}</a></div>
  <div class="panel-body">
    <label class="pull-left">{{$us->email}}</label>
    <a href="{{route('team.invite',[$teamid,$us->id])}}" class="btn btn-warning pull-right">Invite to Team</a>
  </div>
</div>
@endforeach

@endsection

resources/views/user/team/searchuser.blade.php
@extends ('user.layouts.options')

@section('title', ' | Teams - Search User')

@section('content')
<a href="{{ URL::previous() }}" class="btn btn-primary">Back</a><br><br>
<div class="container-fluid">
<form method="post">
  {{csrf_field()}}
<div class="form-group">
  <input type="text" class="form-control" name="search">
  <input type="hidden" name="team_id" value="{{$teamid}}"/>
</div>
<div class="form-group">
    <button type="submit" class="btn btn-primary btn-block">Search</button>
</div>

</form>

@endsection